### PR TITLE
Wrote down 'further steps', as I had to figure them out

### PR DESCRIPTION
**Pull request by pietervdvn**
Hey,

I just got started with both evolution (because of DecSync). As I don't know my way around in Evolution and had to figure out what to do, I wrote it down so that the next person installing won't feel as lost.

### CODE REVIEW

**Comment by pietervdvn** [comment]
BTW: the other steps worked just fine on Ubuntu 18.04.1

**Comment by 39aldo39** [comment]
Thanks! I think more people use Evolution for the first time, so these steps are useful. The way I often add address books (for testing), is by right-clicking an existing one and then selecting `New Address Book`. This is a bit easier, but more counter-intuitive.

I have also edited the steps a bit, mainly to show the possibility of calendars.

**Comment by pietervdvn** [comment]
Superb. I've not yet come around syncing the calendars, but it is on my todo list as well.

Slightly unrelated: I've added categories to my contacts in evolution, but that doesn't show up in Android - I use the default contacts app. Do you -by chance- know a workaround for this?

**Comment by 39aldo39** [comment]
I don't use categories myself, but I will take a look at it.

**Comment by pietervdvn** [comment]
Alright, NP. Thx for the awesome tool!

**Pull request merged**
